apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: schedule-api
spec:
  hosts:
  - schedule-api
  http:
  - route:
    - destination:
        host: schedule-api
    retries:
      attempts: 10
      perTryTimeout: 2s
