version: "3.4"
services:
  tasks-api:
    container_name: tasks-api
    image: rbodonyiil/service-mesh:tasks-api-1.0.0
    build:
      context: ./applications/tasks-api
    ports:
    - 82:10011
  schedule-api:
    container_name: schedule-api
    image: rbodonyiil/service-mesh:schedule-api-1.0.0
    build:
      context: ./applications/schedule-api
    ports:
    - 80:10010
