apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-api-v2
  labels:
    app: schedule-api-v2
spec:
  selector:
    matchLabels:
      app: schedule-api-v2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: schedule-api-v2
    spec:
      containers:
      - name: schedule-api-v2
        image: tap/service-mesh:schedule-api-2.0.0
        imagePullPolicy : Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-api-v2
  labels:
    app: schedule-api-v2
spec:
  type: ClusterIP
  selector:
    app: schedule-api-v2
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
