apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: schedule-api
spec:
  hosts:
  - servicemesh.demo
  http:
  - route:
    - destination:
        host: schedule-api-v2
      weight: 50
    - destination:
        host: schedule-api
      weight: 50
